// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ColorJankenController from "./color_janken_controller"
application.register("color-janken", ColorJankenController)

import GameController from "./game_controller"
application.register("game", GameController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import HiraganaCalcController from "./hiragana_calc_controller"
application.register("hiragana-calc", HiraganaCalcController)
